### ISSUE TITLE
[Bug] More than 11+ locations and network glitches out

### ISSUE THREAD

**Issue by MysticAura** [fredtargaryen/Floocraft#5] opened 2016-11-27 16:13 UTC
MC: 1.10.2
Forge: 2151
Mod: Floocraft-1.7.6

Issue:  If you have over 11 or so locations in your network it's too big for the gui. At this point it tends to mess up and only allow people to go to one of the first few locations. This is happening on a server.

**Comment by fredtargaryen** [comment] 2016-11-27 16:41
Hi, thanks for logging this. I'm pretty snowed under for the next 2 or 3 weeks so unfortunately I can't bring out a fix very quickly, but I will get round to it.

**Comment by MysticAura** [comment] 2016-12-18 16:43
Just a little nudge. Your mod is a favorite on the server and it's a shame we can't make full use of it. Of course rl comes first though.

**Comment by fredtargaryen** [comment] 2016-12-18 18:09
No worries; just started working on it! Glad to hear it :D

**Comment by fredtargaryen** [comment] 2016-12-18 19:41
I've tried this on client and server now, on the version you mentioned. I have 13 different fireplaces but I can go to any of them just fine. I think I need more to go on - please could you provide any screenshots, server logs or Floocraft NBT data? That would be very useful. And does this happen to everyone?

**Comment by MysticAura** [comment] 2016-12-22 19:46
15 on the server, no one can use more than 11 locations (multiplayer or singleplayer) because then it's bigger than the gui. It will send you to one of the first ones usually. Lately we also have nearly a guaranteed server crash when the gui comes up. May help to know that most of us use large gui scale, never auto

[Crash Log](http://pastebin.com/pUdXyjpQ) Next time I'm able to see the gui without the crash, I'll screenshot to show you.

**Comment by fredtargaryen** [comment] 2017-01-28 01:31
Hi,
I've found a PC capable of rendering large GUI Scale, and cannot find this problem on any GUI scale.
Please could you send me a screenshot? I think that is my best chance of finding the problem.
All I can suggest at this point is that you use the latest Forge version, if you don't already.

**Comment by fredtargaryen** [comment] 2019-05-25 10:08
Closed as the issue is outdated and I'm sure I've fixed this anyway. If you still have this problem please reopen the issue or open a new one.

**Closed as completed by fredtargaryen** 2019-05-25 10:08 UTC
Labels: bug
