### ISSUE TITLE
1.14.4 Loader Crash with 1.9.7 "Initializing game"

### ISSUE THREAD

**Issue by Knito58** [fredtargaryen/Floocraft#24] opened 2019-09-21 17:09 UTC
https://pastebin.com/cDYesVwJ
Launched Version: 1.14.4-forge-28.1.10

**Comment by fredtargaryen** [comment] 2019-09-21 18:51
Hi! Thanks for reporting this. This shouldn't be an issue if you use the recommended 28.1.0 instead, but I'll try to make a compatibility build soon.

**Comment by fredtargaryen** [comment] 2019-09-21 19:36
To be clear, are you specifically using [Floocraft 1.14.4-1.9.7.jar](https://www.curseforge.com/minecraft/mc-mods/floocraft/files/2790632)? The dev version won't work.

**Comment by Knito58** [comment] 2019-09-23 17:33
Yes it was the 1.9.7 jar file. Did have the right version I guess. Did not have the dev jar. You can see my file in the paste as ERRORing mod file.

**Comment by Knito58** [comment] 2019-09-24 14:12
Cannot go back to Forge 28.1.0 as other mods demand for 28.1.10 now. Sorry.

**Comment by fredtargaryen** [comment] 2019-09-24 19:05
Hi again,

Please could you try [this jar](https://fredtargaryen.github.io/files/Floocraft%201.14.4-1.9.7.jar?raw=true)? This works fine for me on 28.1.10 with no other mods installed.

**Comment by fuzzyweapon** [comment] 2019-09-24 20:26
I tried it with the new jar (with 28.1.10) you just dropped (granted I have a bunch of other mods on here, but this stack trace doesn't look related).  This happens only client-side, not server-side.

https://pastebin.com/JPf5yGwM

**Comment by Knito58** [comment] 2019-09-24 20:57
28.1.10: https://pastebin.com/niV6C6Xm
28.1.19: https://pastebin.com/Zsytvd3T

Seems to be the same issue for 28.1.10 and 28.1.19 on first review. And is the same as @fuzzyweapon stated. Good news: One fix might work for Forge up to 28.1.19 :)

**Comment by Knito58** [comment] 2019-09-24 21:15
Got the mod loaded with 28.1.19. The particle.manager caught my eye. I made a guess and was right:
It is a problem with optifine. Uninstalling preview_OptiFine_1.14.4_HD_U_F4_pre4.jar lets me use the mod successfully.

**Comment by fredtargaryen** [comment] 2019-09-25 22:34
@Knito58 glad you managed to get it working. It's unfortunate that Optifine is incompatible right now, but I am convinced that this issue is something for the Optifine people to fix rather than me. I will make a note on the Curse page that Optifine is incompatible in 1.14.4.

@fuzzyweapon, are you also using Optifine?

**Comment by fredtargaryen** [comment] 2019-09-29 10:03
The Optifine changelog shows that Optifine U F4 Pre 5 is only compatible with Forge 28.0.93 right now, and the feature which is breaking was introduced after 28.0.93, so this is an Optifine issue rather than a Floocraft one. I'm closing this one now, but thank you for figuring out Optifine was the cause; I'll bear that in mind for future issues.

**Closed as completed by fredtargaryen** 2019-09-29 10:03 UTC
